version: "3"
services:
  database:
    image: mariadb
    ports:
      - 127.0.0.1:2021:3306
    environment:
      MYSQL_ROOT_PASSWORD: justTheDevPassword
      MYSQL_DATABASE: hub

  store:
    image: mongo
    ports:
      - 127.0.0.1:2022:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: justTheDevPassword

  cache:
    image: redis
    ports:
      - 127.0.0.1:2023:6379
